# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Common setup for all lanes"
  before_all do |lane, options|
    xcversion(version: "~> 12.0")
    
    if is_ci?
    else
      Dotenv.overload '.env.secrets'  
    end
  end
  
  desc "Build App"
  private_lane :BUILD do |options|
    time_based_build_number = Time.now.strftime("%y%m%d%H%M")
    build_number = increment_build_number( build_number: time_based_build_number )

    gym(
      project: "VaccineAssistant.xcodeproj",
      scheme: options[:scheme],
      clean: true,
      output_directory: "./output/",
      output_name: "VaccineAssistant-#{options[:configuration]}-#{build_number}.ipa",
      configuration: options[:configuration],
      silent: true,
      export_options: options[:export_options],
    )
  end

  # desc "Deploy App to Testfairy"
  private_lane :DEPLOY do |options|
    api_key = options[:api_key] || ENV['TESTFAIRY_API_KEY']
    testfairy(
      api_key: "#{api_key}",
      testers_groups: options[:testers_groups],
      # notify: "on",
      comment: "" #email_message,
    )
  end

  desc "Build and Deploy App"
  private_lane :BUILD_AND_DEPLOY do |options|
    BUILD(
      base_url: options[:base_url],
      scheme: options[:scheme],
      configuration: options[:configuration],
      export_options: "./fastlane/#{options[:export_options]}"
    )
    DEPLOY(
      testers_groups: options[:testers_groups],
      api_key: options[:api_key]
    )
  end

  desc "Build 10P Dev"
  lane :BUILD_VA_App do |options|
    BUILD_AND_DEPLOY(
      scheme: "VaccineAssistant",
      configuration: "Release",
      export_options: "ExportOptions-inhouse-distribution.plist",
      testers_groups: [""], 
      api_key: options[:api_key]
    )
  end	

end
